Modernize project and theme like napari (#13)
# Description

This modernizes how the project is setup and installed. It drops the
environment.yml and requirements.txt configs and instead creates a
pyproject.toml

This pyproject uses pixi now as will CI, the end result being things
like `pixi run start` spinning up an environment and starting a live
preview of the documentation.

Since the idea of setting up an environment is not currently needed, we
don't have to worry about local installs for the pilot. But I've talked
with folks running workshops (including local napari workshops) and they
have used pixi to great success, so I wanted to set up the framework for
the future way we will likely have environments be set up (with pixi or
uv)

In addition, this adds napari-sphinx-theme and a custom LLM-generated
script builder to turn the mystmd into napari style, complete with both
light and dark theme.

<img width="2149" height="1941" alt="image"
src="https://github.com/user-attachments/assets/b5c9faaf-39ff-490d-a8c7-aa602394ca23"
/>

## Aside

Sweet! Executing notebooks in CI is already proving fruitful! It caught
this deprecation and errored out!

```python

02-extend-napari/05_custom_colormaps.md
  - An exception occurred during code execution, halting further execution:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 3
      1 import napari
----> 3 viewer = napari.view_image(
      4     nuclei,
      5     colormap='blue',
      6     contrast_limits=(0, 0.4)
      7 );
      9 # choose the z slice where nuclei are in focus
     10 viewer.dims.current_step = (30, 0, 0)

File ~/work/workshops/workshops/.pixi/envs/default/lib/python3.14/site-packages/lazy_loader/__init__.py:90, in attach.<locals>.__getattr__(name)
     88     return attr
     89 else:
---> 90     raise AttributeError(f"No {package_name} attribute {name}")

AttributeError: No napari attribute view_image

Site has 1 error and 0 warning, stopping build.

```